config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'index_of_working', to: 'users#index_of_working'
  post 'import', to: 'users#import'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_overtime_approval'
      patch 'attendances/update_overtime_approval'
      get 'attendances/edit_attendance_approval'
      patch 'attendances/update_attendance_approval'
      get 'attendances/attendance_log'
      get 'attendances/edit_onemonth_approval'
      patch 'attendances/update_onemonth_approval'
    end
    resources :attendances, only: :update do
      member do
        get 'attendances/edit_overtime'
        patch 'attendances/update_overtime'
        patch 'attendances/update_onemonth_request'
      end
    end
  end

  resources :bases

end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  validates :employee_number, uniqueness: true
  validates :uid, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # ログイン機能
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save
    end
  end

  def self.updatable_attributes
    [ "name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time",
     "designated_work_end_time", "superior", "admin", "password" ]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:show, :edit, :update, :edit_basic_info, :update_basic_info]
  before_action :admin_user, only: [:index, :index_of_working, :destroy, :edit_basic_info, :update_basic_info]
  before_action :not_admin_user, only: :show
  before_action :superior_or_correct_user, only: :show
  before_action :set_one_month, only: :show
  before_action :set_superiors, only: :show
  
  def index
    if params[:search].present?
      @users = User.where('name LIKE ?', "%#{params[:search]}%").paginate(page: params[:page]) if params[:search].present?
      @h1_title = "検索結果"
    else
      @users = User.paginate(page: params[:page])
      @h1_title = "全ユーザー一覧"
    end
  end

  def index_of_working
    @users = User.joins(:attendances).merge(Attendance.where(worked_on: Date.today).where.not(started_at: nil).where(finished_at: nil))
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil, finished_at: nil).count
    @first_attendance = @attendances.find_by(worked_on: @first_day)
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_posts_csv(@attendances)
      end
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "新規登録しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を編集しました。"
      redirect_to users_path
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    users = User.all
    ActiveRecord::Base.transaction do
      users.each { |user| user.update_attributes!(basic_info_params) }
    end
    flash[:success] = "全ユーザーの基本情報を更新しました。"
    redirect_to root_url
      
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "全ユーザーの基本情報の更新に失敗しました。"
    render :edit_basic_info
  end

  def import
    User.import(params[:file])
    redirect_to users_path
  end
  
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation, :employee_number, :uid, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_work_time, :designated_work_start_time)
    end

    def send_posts_csv(attendances)
      csv_data = CSV.generate do |csv|
        column_names = %w(日付 出勤時間 退勤時間)
        csv << column_names
        @attendances.each do |attendance|
          if attendance.attendance_edit_request == "承認"
            start = l(attendance.started_at, format: :time) if attendance.started_at.present?
            finish = l(attendance.finished_at, format: :time) if attendance.finished_at.present?
            column_values = [
              l(attendance.worked_on, format: :short),
              start,
              finish
            ]
          else
            start = l(attendance.original_started_at, format: :time) if attendance.original_started_at.present?
            finish = l(attendance.original_finished_at, format: :time) if attendance.original_finished_at.present?
            column_values = [
              l(attendance.worked_on, format: :short),
              start,
              finish
            ]
          end
          csv << column_values
        end
      end
      send_data(csv_data, filename: "#{@user.name}_#{@first_day.mon}月_勤怠.csv")
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_info time
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end

  def overtime_work(designated_work_end_time, end_plan_time)
    overtime = format("%.2f", ((end_plan_time - designated_work_end_time) / 60 ) / 60.0).to_f
    if overtime < 0
      overtime += 24.0
    end
    return overtime
  end

  def change_work_date(work_date, work_time)
    Time.new( work_date.year,
              work_date.month,
              work_date.day,
              work_time.hour,
              work_time.min,
              work_time.sec,
              "+09:00"
            )
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages' %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class:"form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-block btn-primary btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, "user--edit") %>
<% provide(:button_text, "編集") %>


<div class="container">
  <h1>アカウント情報の更新</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "EditBasicInfo") %>

<div class="container">
  <h1>基本情報の更新</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true) do |f| %>
        <%= render 'shared/error_messages' %>
        
        <%= f.label :designated_work_start_time, class: "label-basic-info" %>
        <%= f.time_field :designated_work_start_time, class: "form-control" %>
        
        <%= f.label :basic_work_time, class: "label-basic-info" %>
        <%= f.time_field :basic_work_time, class: "form-control" %>
        
        <%= f.submit "編集", class: "btn btn-block btn-primary btn-basic-info" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Index") %>

<div class="container">
  <h1><%= @h1_title %></h1>
  
  <div class="row">
    <div class="index-form">
      <%= form_with url: users_path, method: :get, local: true do |f| %>
        <%= f.label :search, "ユーザー名検索", class: "user-index-label" %>
        <%= f.text_field :search, placeholder: "キーワードを入力", class: "form-inline" %>
        <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
      <% end %>
    </div>

    <%= form_with url: import_path, local: true do |f| %>
      <%= f.file_field :file , class: "index-file" %>
      <%= f.submit "CSVをインポート", class: "btn btn-lg btn-primary user-index-btn" %>
    <% end %>


    <div class="col-md-10 col-md-offset-1">
      <%= will_paginate %>
      
        <table class="table table-condenced table-hover" id="table-users">
          <% @users.each do |user| %>
            <% if current_user.admin? && !current_user?(user) %>
              <tr>
                <td><%= user.name %></td>
              </tr>
              <tr>
                <td>

                  <%= link_to "削除", user, method: :delete,
                  data: { confirm: "削除してよろしいですか？" },
                  class: "btn btn-primary" %>
                
                </td>
              </tr>
              <tr>
                <td>
                  <button type="button" class="btn btn-primary btn-lg" data-toggle="collapse" data-target="#collapse<%= user.id %>">編集</button>
                  <div id="collapse<%= user.id %>" class="collapse">
                    <div class="panel panel-default">
                      <div class="panel-body">
                        <%= form_with(model: user, local: true) do |f| %>
  
                          <%= f.label :name, class: "label-index" %>
                          <%= f.text_field :name, class: "form-control" %>
  
                          <%= f.label :email, class: "label-index" %>
                          <%= f.email_field :email, class: "form-control" %>
  
                          <%= f.label :affiliation, class: "label-index" %>
                          <%= f.text_field :affiliation, class: "form-control" %>
  
                          <%= f.label :password, class: "label-index" %>
                          <%= f.password_field :password, class:"form-control" %>
  
                          <%= f.label :password_confirmation, class: "label-index" %>
                          <%= f.password_field :password_confirmation, class: "form-control" %>

                          <%= f.label :employee_number, class: "label-index" %>
                          <%= f.text_field :employee_number, class: "form-control" %>

                          <%= f.label :uid, class: "label-index" %>
                          <%= f.text_field :uid, class: "form-control" %>

                          <%= f.label :basic_work_time, class: "label-index" %>
                          <%= f.time_field :basic_work_time, class: "form-control" %>

                          <%= f.label :designated_work_start_time, class: "label-index" %>
                          <%= f.time_field :designated_work_start_time, class: "form-control" %>

                          <%= f.label :designated_work_end_time, class: "label-index" %>
                          <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
                          <%= f.submit "編集", class: "btn btn-block btn-primary btn-index" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
      <% will_paginate %>
    </div>
  </div>
</div>

app/views/users/index_of_working.html.erb
<% provide(:title, "working user") %>

<div class="container">
  <h1>出勤中社員一覧</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table class="table table-bordered table-users">
        <thead>
          <tr>
            <th>社員番号</th>
            <th>名前</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.employee_number %></td>
              <td><%= user.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "signup") %>
<% provide(:class_text, "signup") %>
<% provide(:button_text, "新規作成") %>


<div class="container">
  <h1>アカウント作成</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="container">
  <table class="table table-bordered table-condenced user-table">
    <tr>
      <td>
        <% if current_user?(@user) %>
          <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-default btn-primary" %>
        <% end %>
          <%= l(@first_day, format: :middle) %>   時間管理表   
        <% if current_user?(@user) %>
          <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-default btn-primary" %>
        <% end %>
      </td>
      <td>
        指定勤務開始時間：<%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間：<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3">基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td>初日　<%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.employee_number %></td>
      <td>出勤日数　<%= @worked_sum %>日</td>
      <td>締め　<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
  <% if @user.superior? && current_user?(@user) %>
    <p>
      <% onemonth_attendance = Attendance.where(onemonth_approval_request: "申請中").where(onemonth_approval_superior: current_user.name) %>
      <% if onemonth_attendance.present? %>
        <%= link_to "【所属長承認申請のお知らせ】", attendances_edit_onemonth_approval_user_path(@user), remote: true %>
        <span class="superior-notification">
          <%= onemonth_attendance.count %>件の通知があります。
        </span>
      <% else %>
        【所属長承認申請のお知らせ】
      <% end %>
    </p>
    <p>
      <% edit_attendance = Attendance.where(attendance_edit_request: "申請中").where(edit_approval_superior: current_user.name) %>
      <% if edit_attendance.present?%>
        <%= link_to "【勤怠変更申請のお知らせ】", attendances_edit_attendance_approval_user_path(@user), remote: true %>
        <span class="superior-notification">
          <%= edit_attendance.count %>件の通知があります。
        </span>
      <% else %>
        【勤怠変更申請のお知らせ】
      <% end %>
    </p>
    <p>
      <% overtime_attendance = Attendance.where(overtime_request: "申請中").where(overtime_superior: current_user.name)%>
      <% if overtime_attendance.present? %>
        <%= link_to "【残業申請のお知らせ】", attendances_edit_overtime_approval_user_path(@user), remote: true %>
        <span class="superior-notification">
          <%= overtime_attendance.count %>件の通知があります。
        </span>
      <% else %>
        【残業申請のお知らせ】
      <% end %>
    </p>
  <% end %>
  <% if current_user?(@user) %>
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-default btn-users-show btn-primary" %>
    <%= link_to "CSV出力", user_path(@user, format: :csv), class: "btn btn-default btn-users-show btn-primary" %><br>
    <%= link_to "勤怠修正ログ（承認済）", attendances_attendance_log_user_path, class: "btn btn-default btn-users-show btn-primary" %>
  <% end %>

  
  <table class="table table-bordered table-condenced table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th> </th>
        <th>時</th>
        <th>分</th>
        <th> </th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td>
            <% if current_user?(@user) %>
              <%= link_to "残業申請", attendances_edit_overtime_user_attendance_path(@user, day), remote: true, class: "btn btn-default btn-primary" %>
            <% end %>
          </td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= day_color(day.worked_on.wday) %>-color"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= day.started_at.hour if day.started_at.present? %></td>
          <td><%= times_15_min_round_up(day.started_at.min) if day.started_at.present? %></td>
          <td>
            <% if current_user?(@user) %>
              <% if (Date.current == day.worked_on) && day.started_at.nil? %>
                <%= link_to "出勤登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-attendance" %>
              <% end %>
            <% end %>
          </td>
          <td><%= day.finished_at.hour if day.finished_at.present? %></td>
          <td><%= times_15_min_round_up(day.finished_at.min) if day.finished_at.present? %></td>
          <td>
            <% if current_user?(@user) %>
              <% if (Date.current == day.worked_on) && day.started_at.present? && day.finished_at.nil? %>
                <%= link_to "退勤登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-attendance" %>
              <% end %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_times = @total_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.end_plan_time.hour if day.end_plan_time.present? %></td>
          <td><%= day.end_plan_time.min if day.end_plan_time.present? %></td>
          <td><%= overtime_work(change_work_date(day.worked_on, @user.designated_work_end_time), day.end_plan_time) if day.end_plan_time.present? %></td>
          <td><%= day.overtime_note if day.overtime_note.present? %></td>
          <td>
            <% if day.overtime_request.present? && (day.overtime_request != "なし") %>
              <% if day.overtime_request == "申請中" %>
                <%= day.overtime_superior %>へ
              <% else %>
                <%= day.overtime_superior %>より
              <% end %>
              残業<%= day.overtime_request %>
            <% end %>
            <br>
            <% if day.attendance_edit_request.present? && (day.attendance_edit_request != "なし") %>
              <% if day.attendance_edit_request == "申請中" %>
                <%= day.edit_approval_superior %>へ
              <% else %>
                <%= day.edit_approval_superior %>より
              <% end %>
              勤怠編集<%= day.attendance_edit_request %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td><%= @total_times %></td>
        <td colspan="5"></td>
        <td>
          所属長確認<br>
          <% if @first_attendance.onemonth_approval_request.present? %>
            <%= @first_attendance.onemonth_approval_request %>
          <% else %>
            未
          <% end %>
          <br>
          <% if current_user?(@user) %><%= form_with model: @first_attendance, url: attendances_update_onemonth_request_user_attendance_path(@user, @first_attendance), local: true do |f| %>
            <%= f.collection_select :onemonth_approval_superior, @superiors, :name, :name , { prompt: "選択" }, class: "select-users" %><br>
              <%= f.hidden_field :onemonth_approval_request, :value => "申請中" %>
              <%= f.submit "申請", class: "btn btn-default btn-primary" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

<div id="edit-overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-overtime-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-attendance-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-onemonth-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>