config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'index_of_working', to: 'users#index_of_working'
  post 'import', to: 'users#import'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_overtime_approval'
      patch 'attendances/update_overtime_approval'
      get 'attendances/edit_attendance_approval'
      patch 'attendances/update_attendance_approval'
      get 'attendances/attendance_log'
      get 'attendances/edit_onemonth_approval'
      patch 'attendances/update_onemonth_approval'
    end
    resources :attendances, only: :update do
      member do
        get 'attendances/edit_overtime'
        patch 'attendances/update_overtime'
        patch 'attendances/update_onemonth_request'
      end
    end
  end

  resources :bases

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  validates :overtime_note, length: { maximum: 100 }
  
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  validate :started_at_is_invalid_without_a_finished_at, on: :update_one
  validate :end_plan_time_is_invalid_if_fast_than_designated_work_end_time, on: :update_overtime
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です。") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      if (started_at > finished_at) && (attendance_next_day == false)
        errors.add(:started_at, "より早い退勤時間は無効です。")
      end
    end
  end
  
  def started_at_is_invalid_without_a_finished_at
    errors.add(:finished_at, "が必要です。") if finished_at.blank? && started_at.present?
  end

  def end_plan_time_is_invalid_if_fast_than_designated_work_end_time
    if (end_plan_time < change_work_date(worked_on, user.designated_work_end_time)) && overtime_next_day == false
      errors.add(:end_plan_time, "が不正な値です。")
    end
  end

  def change_work_date(work_date, work_time)
    Time.new( work_date.year,
              work_date.month,
              work_date.day,
              work_time.hour,
              work_time.min,
              work_time.sec,
              "+09:00"
            )
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :edit_overtime_approval, :update_overtime_approval, :edit_attendance_approval, :update_attendance_approval, :attendance_log, :edit_onemonth_approval, :update_onemonth_approval]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :correct_user, only: [:edit_one_month, :update_one_month, :attendance_log]
  before_action :superior_user, only: [:edit_overtime_approval, :update_overtime_approval, :edit_attendance_approval, :update_attendance_approval, :edit_onemonth_approval, :update_onemonth_approval]
  before_action :not_admin_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month
  before_action :set_superiors, only: [:edit_one_month, :update_one_month]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0), original_started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0), original_finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れさまでした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        if item[:started_at].present?
          item[:started_at] = change_work_date(attendance.worked_on, item[:started_at].to_time)
        end
        if item[:finished_at].present?
          if item[:attendance_next_day] == "1"
            item[:finished_at] = change_work_date(attendance.worked_on, item[:finished_at].to_time) + 86400
          else
            item[:finished_at] = change_work_date(attendance.worked_on, item[:finished_at].to_time)
          end
        end
        attendance.attributes = item
        if item[:edit_approval_superior].present?
          attendance.attendance_edit_request = "申請中"
        end
        attendance.save!(context: :update_one)  # この時だけon: :update_oneになっているバリデーションを実行する、save!で例外発生させてrescueに渡す
      end
    end
    flash[:success] = "1か月分の勤怠情報を更新しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあったため、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end

  def edit_overtime
    @user = User.find_by(id: params[:user_id])
    @superiors = User.where(superior: true).where.not(id: @user.id)
    @attendance = @user.attendances.find(params[:id])
  end

  def update_overtime
    @user = User.find_by(id: params[:user_id])
    if overtime_params[:end_plan_time].present? && overtime_params[:overtime_superior].present?
      @attendance = @user.attendances.find(params[:id])
      if overtime_params[:overtime_next_day] == "1"
        end_time = change_work_date(@attendance.worked_on, overtime_params[:end_plan_time].to_time) + 86400
      else
        end_time = change_work_date(@attendance.worked_on, overtime_params[:end_plan_time].to_time)
      end
      @attendance.end_plan_time = end_time
      @attendance.overtime_next_day = overtime_params[:overtime_next_day]
      @attendance.overtime_note = overtime_params[:overtime_note]
      @attendance.overtime_superior = overtime_params[:overtime_superior]
      if @attendance.save(context: :update_overtime)
        @attendance.overtime_request = "申請中"
        @attendance.save
        flash[:success] = "残業申請しました。"
      else
        flash[:danger] = "残業申請に失敗しました。"
      end
    elsif overtime_params[:end_plan_time].blank? && overtime_params[:overtime_superior].present?
      flash[:danger] = "終了予定時刻を入力してください。"
    elsif overtime_params[:end_plan_time].present? && overtime_params[:overtime_superior].blank?
      flash[:danger] = "上長を選択してください。"
    else
      flash[:danger] = "終了予定時刻を入力し、上長を選択してください。"
    end
    redirect_to @user
  end

  def edit_overtime_approval
    @users = User.joins(:attendances).merge(Attendance.where(overtime_superior: @user.name).where(overtime_request: "申請中")).group(:user_id)
  end

  def update_overtime_approval
    overtime_approval_params.each do |id, item|
      if item[:overtime_change] == "1"
        attendance = Attendance.find(id)
        if item[:overtime_request] == "なし"
          attendance.end_plan_time = nil
          attendance.overtime_next_day = nil
          attendance.overtime_note = nil
          attendance.overtime_superior = nil
          attendance.overtime_request = nil
          attendance.save
        else
          attendance.overtime_request = item[:overtime_request]
          attendance.save
        end
      end
    end
    redirect_to @user
  end

  def edit_attendance_approval
    @users = User.joins(:attendances).merge(Attendance.where(edit_approval_superior: @user.name).where(attendance_edit_request: "申請中")).group(:user_id)
  end

  def update_attendance_approval
    attendances_approval_params.each do |id, item|
      if item[:attendance_edit_change] == "1"
        attendance = Attendance.find(id)
        if item[:attendance_edit_request] == "なし"
          attendance.started_at = attendance.original_started_at
          attendance.finished_at = attendance.original_finished_at
          attendance.note = nil
          attendance.edit_approval_superior = nil
          attendance.attendance_edit_request = "なし"
          attendance.save
        else
          attendance.attendance_edit_request = item[:attendance_edit_request]
          attendance.edit_approval_day = Date.today
          attendance.save
        end
      end
    end
    redirect_to @user
  end

  def attendance_log
    if params[:month].present?
      first_day = (params[:month] + "-1").to_date
      last_day = first_day.end_of_month
      this_month = [first_day..last_day]
    end
    @attendances = @user.attendances.where(worked_on: this_month).where(attendance_edit_request: "承認")
  end

  def update_onemonth_request
    @user = User.find(params[:user_id])
    if onemonth_request_params[:onemonth_approval_superior].present?
      attendance = Attendance.find(params[:id])
      if attendance.update_attributes(onemonth_request_params)
        flash[:success] = "所属長承認申請しました。"
      else
        flash[:danger] = "所属長承認申請に失敗しました。"
      end
    else
      flash[:danger] = "上長を選択してください。"
    end
    redirect_to @user
  end

  def edit_onemonth_approval
    @users = User.joins(:attendances).merge(Attendance.where(onemonth_approval_superior: @user.name).where(onemonth_approval_request: "申請中")).group(:user_id)
  end

  def update_onemonth_approval
    onemonth_approval_params.each do |id, item|
      if item[:onemonth_approval_change] == "1"
        attendance = Attendance.find(id)
        if item[:onemonth_approval_request] == "なし"
          attendance.onemonth_approval_superior = nil
          attendance.onemonth_approval_request = nil
          attendance.save
        else
          attendance.onemonth_approval_request = item[:onemonth_approval_request]
          attendance.save
        end
      end
    end
    redirect_to @user
  end
  
  private
    
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note,:attendance_next_day, :edit_approval_superior])[:attendances]
    end

    def attendances_approval_params
      params.require(:user).permit(attendances: [:attendance_edit_request, :attendance_edit_change])[:attendances]
    end

    def overtime_params
      params.require(:attendance).permit(:end_plan_time, :overtime_next_day, :overtime_note, :overtime_superior)
    end

    def overtime_approval_params
      params.require(:user).permit(attendances: [:overtime_request, :overtime_change])[:attendances]
    end

    def onemonth_request_params
      params.require(:attendance).permit(:onemonth_approval_superior, :onemonth_approval_request)
    end

    def onemonth_approval_params
      params.require(:user).permit(attendances: [:onemonth_approval_request, :onemonth_approval_change])[:attendances]
    end

    def change_work_date(work_date, work_time)
      Time.new( work_date.year,
                work_date.month,
                work_date.day,
                work_time.hour,
                work_time.min,
                work_time.sec,
                "+09:00"
              )
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def times_15_min_round_up(time)
    if time < 15
      time = 0
    elsif time < 30
      time = 15
    elsif time < 45
      time = 30
    else
      time = 45
    end
  end
end

app/views/attendances/_edit_attendance_approval.html.erb
<% provide(:title, "勤怠変更承認") %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with model: @user, url: attendances_update_attendance_approval_user_path(@user), local: true, method: :patch do |f| %>
            <% @users.each do |user|%>
              <table class="table table-condenced table-bordered table-hover" id="table-edit-approval">
                <h1 class="modal-title">【<%= user.name %>からの勤怠変更申請】</h1>
                <thead>
                  <tr>
                    <th rowspan="3">日付</th>
                    <th rowspan="3">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3">備考</th>
                    <th rowspan="3">指示者確認㊞</th>
                    <th rowspan="3">変更</th>
                    <th rowspan="3">勤怠を確認する</th>
                  </tr>
                  <tr>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                  </tr>
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances = user.attendances.where(attendance_edit_request: "申請中").where(edit_approval_superior: @user.name).order(:worked_on) %>
                  <% attendances.each do |attendance| %>  
                    <%= f.fields_for "attendances[]", attendance do |a| %>
                      <tr>
                        <td><%= l(attendance.worked_on, format: :short) %></td>
                        <td><%= $days_of_the_week[attendance.worked_on.wday] %></td>
                        <% if attendance.original_started_at.present? %>
                          <td><%= attendance.original_started_at.hour %></td>
                          <td><%= attendance.original_started_at.min %></td>
                        <% else %>
                          <td></td>
                          <td></td>
                        <% end %>
                        <% if attendance.original_finished_at.present? %>
                          <td><%= attendance.original_finished_at.hour %></td>
                          <td><%= attendance.original_finished_at.min %></td>
                        <% else %>
                          <td></td>
                          <td></td>
                        <% end %>
                        <td><%= attendance.started_at.hour %></td>
                        <td><%= attendance.started_at.min %></td>
                        <td><%= attendance.finished_at.hour %></td>
                        <td><%= attendance.finished_at.min %></td>
                        <td><%= attendance.note %></td>
                        <td><%= a.select :attendance_edit_request, [["申請中", "申請中"], ["なし", "なし"], ["承認", "承認"], ["否認", "否認"]] %></td>
                        <td><%= a.check_box :attendance_edit_change %></td>
                        <td><%= link_to "確認", user, class: "btn btn-primary btn-sm" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            <% end %>
            <%= f.submit "変更を送信する", class: "btn btn-primary btn-lg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_onemonth_approval.html.erb
<% provide(:title, "勤怠承認") %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with model: @user, url: attendances_update_onemonth_approval_user_path(@user), local: true, method: :patch do |f| %>
            <% @users.each do |user|%>
              <table class="table table-condenced table-bordered table-hover" id="table-onemonth-approval">
                <h1 class="modal-title">【<%= user.name %>からの1か月分の勤怠申請】</h1>
                <thead>
                  <tr>
                    <th>月</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances = user.attendances.where(onemonth_approval_request: "申請中").where(onemonth_approval_superior: @user.name).order(:worked_on) %>
                  <% attendances.each do |attendance| %>  
                    <%= f.fields_for "attendances[]", attendance do |a| %>
                      <tr>
                        <td><%= attendance.worked_on.mon %>月</td>
                        <td><%= a.select :onemonth_approval_request, [["申請中", "申請中"], ["なし", "なし"], ["承認", "承認"], ["否認", "否認"]] %></td>
                        <td><%= a.check_box :onemonth_approval_change %></td>
                        <td><%= link_to "確認", user, class: "btn btn-primary btn-sm" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            <% end %>
            <%= f.submit "変更を送信する", class: "btn btn-primary btn-lg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime.html.erb
<% provide(:title, "残業申請") %>
<% provide(:button_text, "更新") %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">【残業申請】</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= form_with model: @attendance, url: attendances_update_overtime_user_attendance_path(date: @attendance.worked_on), local: true, method: :patch do |f| %>
            <table class="table table-condenced table-bordered" id="table-overtime">
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>指示者確認㊞</th>
                </tr>
              </thead>
              <tbody>
                
                  <tr>
                    <td><%= l(@attendance.worked_on, format: :short) %></td>
                    <td><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
                    <td><%= f.time_field :end_plan_time, class: "form-control" %></td>
                    <td><%= f.check_box :overtime_next_day %></td>
                    <td><%= f.text_field :overtime_note, class: "form-control" %></td>
                    <td><%= f.collection_select :overtime_superior, @superiors, :name, :name, { prompt: "選択" } %></td>
                  </tr>
                
              </tbody>
            </table>
            <%= f.submit "変更を送信する", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime_approval.html.erb
<% provide(:title, "残業承認") %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with model: @user, url: attendances_update_overtime_approval_user_path(@user), local: true, method: :patch do |f| %>
            <% @users.each do |user|%>
              <table class="table table-condenced table-bordered table-hover" id="table-overtime-approval">
                <h1 class="modal-title">【<%= user.name %>からの残業申請】</h1>
                <thead>
                  <tr>
                    <th>日付</th>
                    <th>曜日</th>
                    <th>終了予定時間</th>
                    <th>指定勤務終了時間</th>
                    <th>時間外時間</th>
                    <th>業務処理内容</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances = user.attendances.where(overtime_request: "申請中").where(overtime_superior: @user.name).order(:worked_on) %>
                  <% attendances.each do |attendance| %>  
                    <%= f.fields_for "attendances[]", attendance do |a| %>
                      <tr>
                        <td><%= l(attendance.worked_on, format: :short) %></td>
                        <td><%= $days_of_the_week[attendance.worked_on.wday] %></td>
                        <td><%= l(attendance.end_plan_time, format: :time) %></td>
                        <td><%= l(user.designated_work_end_time, format: :time) %></td>
                        <td><%= overtime_work(change_work_date(attendance.worked_on, user.designated_work_end_time), attendance.end_plan_time) %></td>
                        <td><%= attendance.overtime_note %></td>
                        <td><%= a.select :overtime_request, [["申請中", "申請中"], ["なし", "なし"], ["承認", "承認"], ["否認", "否認"]] %></td>
                        <td><%= a.check_box :overtime_change %></td>
                        <td><%= link_to "確認", user, class: "btn btn-primary btn-sm" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            <% end %>
            <%= f.submit "変更を送信する", class: "btn btn-primary btn-lg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/attendance_log.html.erb
<% provide(:title, @user.name) %>

<div class="container">
  <h1>勤怠ログ</h1>
  <div class="row">
    <%= form_with url: attendances_attendance_log_user_path(@user), method: :get, local: true do |f| %>
      <%= f.month_field :month %>
      <%= f.submit "検索", class: "btn btn-primary btn-sm" %>
    <% end %>
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-bordered table-condenced table-hover" id="table-log">
        <thead>
          <tr>
            <th>日付</th>
            <th>変更前出社時間</th>
            <th>変更前退社時間</th>
            <th>変更後出社</th>
            <th>変更後退社</th>
            <th>指示者</th>
            <th>承認日</th>
          </tr>
        </thead>
        <tbody>
          <% @attendances.each do |attendance| %>
            <tr>
              <td><%= l(attendance.worked_on, format: :short) %></td>
              
              <td>
                <% if attendance.original_started_at.present? %>
                  <%= l(attendance.original_started_at, format: :time) %>
                <% end %>
              </td>
              <td>
                <% if attendance.original_finished_at.present? %>
                  <%= l(attendance.original_finished_at, format: :time) %>
                <% end %>
              </td>
              <td><%= l(attendance.started_at, format: :time) %></td>
              <td><%= l(attendance.finished_at, format: :time) %></td>
              <td><%= attendance.edit_approval_superior %></td>
              <td><%= l(attendance.edit_approval_day, format: :short) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/attendances/edit_attendance_approval.js.erb
$("#edit-attendance-approval").html("<%= escape_javascript(render 'edit_attendance_approval') %>");
$("#edit-attendance-approval").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>

<div class="container">
  <h1>勤怠編集画面</h1>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
        <table class="table table-bordered table-condenced table-hover" id="table-attendances">
          <thead>
            <tr>
              <th>日付</th>
              <th>曜日</th>
              <th>出社</th>
              <th>退社</th>
              <th>翌日</th>
              <th>在社時間</th>
              <th>備考</th>
              <th>指示者確認㊞</th>
            </tr>
          </thead>
          <tbody>
            <% @attendances.each do |day| %>
              <%= f.fields_for "attendances[]", day do |attendance| %>
                <tr>
                  <td><%= l(day.worked_on, format: :short) %></td>
                  <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                  <% if Date.current < day.worked_on %>
                    <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                    <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
                  <% else %>
                    <td><%= attendance.time_field :started_at, class: "form-control" %></td>
                    <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
                  <% end %>
                  <td><%= attendance.check_box :attendance_next_day %></td>
                  <td>
                    <% if day.started_at.present? && day.finished_at.present? %>
                      <%= working_times(day.started_at, day.finished_at) %>
                    <% end %>
                  </td>
                  <td><%= attendance.text_field :note, class: "form-control" %></td>
                  <td><%= attendance.collection_select :edit_approval_superior, @superiors, :name, :name, { prompt: "選択" } %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <div class="center">
          <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default btn-primary" %>
          <%= f.submit "編集を保存する", class: "btn btn-lg btn-default btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/edit_onemonth_approval.js.erb
$("#edit-onemonth-approval").html("<%= escape_javascript(render 'edit_onemonth_approval') %>");
$("#edit-onemonth-approval").modal("show");

app/views/attendances/edit_overtime.js.erb
$("#edit-overtime").html("<%= escape_javascript(render 'edit_overtime') %>");
$("#edit-overtime").modal("show");

app/views/attendances/edit_overtime_approval.js.erb
$("#edit-overtime-approval").html("<%= escape_javascript(render 'edit_overtime_approval') %>");
$("#edit-overtime-approval").modal("show");